### ISSUE TITLE
the program crashes

### ISSUE THREAD

**Issue by AntonUden** [Hagmar/Helix#2]
Fetching server time
Fetching token
Game token received: 6cd11d4ba7dd5fa4da4dbddc2ba6ccc3
Waiting to simulate gameplay...
Saving score
State hash: 6f42943bbbd40c72f5641ef3f108e74f
Traceback (most recent call last):
  File "helix.py", line 198, in <module>
    main()
  File "helix.py", line 193, in main
    set_score(udid, args.score)
  File "helix.py", line 38, in set_score
    save_score(udid, token, score=score)
  File "helix.py", line 132, in save_score
    session = calculate_session()
  File "helix.py", line 163, in calculate_session
    sync_start_time = datetime.datetime.now().timestamp()
AttributeError: 'datetime.datetime' object has no attribute 'timestamp'

**Comment by AntonUden** [comment]
i used the wrong version of python
